# Generated by Django 4.2.18 on 2025-03-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_poll_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('full', 'Full Width')], default='center', max_length=20),
        ),
    ]
